---
- name: Port State Event from network
  hosts: all
  sources:
   - ansible.eda.kafka:
       host: 3.141.230.190
       port: 9092
       topic: networks
  rules:           
    - name: Run 'hello_eda.yml' To Bring Up Interface
      condition: event.body.fields.admin_status == "DOWN"
      action:
        run_playbook:
          name: "hello_eda.yml"
          post_events: true
          extra_vars:
            limit: ansible_eda.event.body.tags.source
    - name: Run 'hello_debug.yml' To Debug 'event.body.fields'
      condition: event.body.fields.admin_status == "UP"
      action:
        run_playbook:
          name: "hello_debug.yml"
