---
- name: Port State Event from network
  hosts: all
  sources:
   - ansible.eda.kafka:
       host: 3.141.230.190
       port: 9092
       topic: networks
  rules:           
    - name: Run 'Interface Up' Job Template To Bring Up Interface
      condition: event.body.fields.admin_status == "DOWN"
      action:
        run_job_template:
          organization: "Default"
          name: "Interface Up"
          post_events: true
          job_args:
            extra_vars:
              limit: ansible_eda.event.body.tags.source
    - name: Run 'Debug - event.body.fields' To Debug 'event.body.fields'
      condition: event.body.fields.admin_status == "UP"
      action:
        run_job_template:
          organization: "Default"
          name: "Debug - event.body.fields"
          post_events: true
          job_args:
            extra_vars:
              limit: ansible_eda.event.body.tags.source
