---
- name: DEBUG Playbook
  hosts: "{{ ansible_eda.event.body.tags.source }}"
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Show Interface Status
      debug:
        msg: "Interface {{ ansible_eda.event.body.name }} is {{ ansible_eda.event.body.fields }}"
